server:
  port: 8888
  
spring:
 cloud:   config:
     server:
        encrypt:          enabled: false
        git:
          uri: https://github.com/gabrielsm14/microservice-repo
          search-paths: fornecedor, loja, transportador

#spring:#  profiles:#    active: native#  cloud:#    config:#      server:#        native:#          search-locations: C:\microservice-repo
              
          
    
    
    
    
    
    
    
    
    
    
    
           
     